# Generated by Django 3.2.4 on 2021-06-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sec_teacherprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='section',
        ),
        migrations.DeleteModel(
            name='Sec',
        ),
    ]
