# Generated by Django 3.2.4 on 2021-06-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
