# Generated by Django 3.2.4 on 2021-06-19 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sec'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='teacher', max_length=100)),
                ('password', models.CharField(default='12345678', max_length=50)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dep')),
                ('sec_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sec')),
            ],
        ),
    ]
