# Generated by Django 3.2.4 on 2021-06-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='username',
            field=models.CharField(default='students', max_length=100),
        ),
    ]
