# Generated by Django 3.2.4 on 2021-06-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_studentprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='password',
            field=models.CharField(default='1234', max_length=50),
        ),
    ]
