# Generated by Django 3.2.4 on 2021-06-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_techermainprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techermainprofile',
            old_name='reaserce_detail',
            new_name='reaserch_detail',
        ),
    ]
