# Generated by Django 3.2.4 on 2021-07-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_reaserce_detail_techermainprofile_reaserch_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsMainProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(max_length=100)),
                ('attndence', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studentprofile')),
            ],
        ),
    ]
