# Generated by Django 3.2.4 on 2021-07-03 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_studentsattendence_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsattendence',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
