# Generated by Django 3.2.4 on 2021-07-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_studentsattendence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='dept_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sec_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsattendence',
            name='attndence',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='studentsattendence',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentsattendence',
            name='username',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
