# Generated by Django 3.2.4 on 2021-07-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210704_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsattendence',
            name='attndence',
            field=models.BooleanField(default=False),
        ),
    ]
