# Generated by Django 3.2.4 on 2021-07-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_studentsattendence_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsAttendence',
        ),
    ]
