# Generated by Django 3.2.4 on 2021-07-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_delete_studentsattendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendencemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('attendence', models.BooleanField(default=False)),
            ],
        ),
    ]
