# Generated by Django 3.2.4 on 2021-07-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_attendencemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendencemodel',
            name='attendence',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
