# Generated by Django 3.2.4 on 2021-07-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_studentprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvulate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(default='', max_length=100)),
                ('student_name', models.CharField(default='', max_length=100)),
                ('evulotion', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
